const d4 = ["http://localhost/login/Kasp_proj_new/dice/4_1.png",
"http://localhost/login/Kasp_proj_new/dice/4_2.png",
"http://localhost/login/Kasp_proj_new/dice/4_3.png",
"http://localhost/login/Kasp_proj_new/dice/4_4.png"];

const d6 = ["http://localhost/login/Kasp_proj_new/dice/6_1.png",
"http://localhost/login/Kasp_proj_new/dice/6_2.png",
"http://localhost/login/Kasp_proj_new/dice/6_3.png",
"http://localhost/login/Kasp_proj_new/dice/6_4.png",
"http://localhost/login/Kasp_proj_new/dice/6_5.png",
"http://localhost/login/Kasp_proj_new/dice/6_6.png"];

const d8 = ["http://localhost/login/Kasp_proj_new/dice/8_1.png",
"http://localhost/login/Kasp_proj_new/dice/8_2.png",
"http://localhost/login/Kasp_proj_new/dice/8_3.png",
"http://localhost/login/Kasp_proj_new/dice/8_4.png",
"http://localhost/login/Kasp_proj_new/dice/8_5.png",
"http://localhost/login/Kasp_proj_new/dice/8_6.png",
"http://localhost/login/Kasp_proj_new/dice/8_7.png",
"http://localhost/login/Kasp_proj_new/dice/8_8.png"];

const d10 = ["http://localhost/login/Kasp_proj_new/dice/10_1.png",
"http://localhost/login/Kasp_proj_new/dice/10_2.png",
"http://localhost/login/Kasp_proj_new/dice/10_3.png",
"http://localhost/login/Kasp_proj_new/dice/10_4.png",
"http://localhost/login/Kasp_proj_new/dice/10_5.png",
"http://localhost/login/Kasp_proj_new/dice/10_6.png",
"http://localhost/login/Kasp_proj_new/dice/10_7.png",
"http://localhost/login/Kasp_proj_new/dice/10_8.png",
"http://localhost/login/Kasp_proj_new/dice/10_9.png",
"http://localhost/login/Kasp_proj_new/dice/10_10.png"];

const d12 = ["http://localhost/login/Kasp_proj_new/dice/12_1.png",
"http://localhost/login/Kasp_proj_new/dice/12_2.png",
"http://localhost/login/Kasp_proj_new/dice/12_3.png",
"http://localhost/login/Kasp_proj_new/dice/12_4.png",
"http://localhost/login/Kasp_proj_new/dice/12_5.png",
"http://localhost/login/Kasp_proj_new/dice/12_6.png",
"http://localhost/login/Kasp_proj_new/dice/12_7.png",
"http://localhost/login/Kasp_proj_new/dice/12_8.png",
"http://localhost/login/Kasp_proj_new/dice/12_9.png",
"http://localhost/login/Kasp_proj_new/dice/12_10.png",
"http://localhost/login/Kasp_proj_new/dice/12_10.png",
"http://localhost/login/Kasp_proj_new/dice/12_11.png",
"http://localhost/login/Kasp_proj_new/dice/12_12.png"];

const d20 = ["http://localhost/login/Kasp_proj_new/dice/20_1.png",
"http://localhost/login/Kasp_proj_new/dice/20_2.png",
"http://localhost/login/Kasp_proj_new/dice/20_3.png",
"http://localhost/login/Kasp_proj_new/dice/20_4.png",
"http://localhost/login/Kasp_proj_new/dice/20_4.png",
"http://localhost/login/Kasp_proj_new/dice/20_5.png",
"http://localhost/login/Kasp_proj_new/dice/20_6.png",
"http://localhost/login/Kasp_proj_new/dice/20_7.png",
"http://localhost/login/Kasp_proj_new/dice/20_8.png",
"http://localhost/login/Kasp_proj_new/dice/20_9.png",
"http://localhost/login/Kasp_proj_new/dice/20_10.png",
"http://localhost/login/Kasp_proj_new/dice/20_11.png",
"http://localhost/login/Kasp_proj_new/dice/20_12.png",
"http://localhost/login/Kasp_proj_new/dice/20_13.png",
"http://localhost/login/Kasp_proj_new/dice/20_14.png",
"http://localhost/login/Kasp_proj_new/dice/20_15.png",
"http://localhost/login/Kasp_proj_new/dice/20_16.png",
"http://localhost/login/Kasp_proj_new/dice/20_17.png",
"http://localhost/login/Kasp_proj_new/dice/20_18.png",
"http://localhost/login/Kasp_proj_new/dice/20_19.png",
"http://localhost/login/Kasp_proj_new/dice/20_20.png"];

const d100 = ["http://localhost/login/Kasp_proj_new/dice/10_1.png",
"http://localhost/login/Kasp_proj_new/dice/10_2.png",
"http://localhost/login/Kasp_proj_new/dice/10_3.png",
"http://localhost/login/Kasp_proj_new/dice/10_4.png",
"http://localhost/login/Kasp_proj_new/dice/10_5.png",
"http://localhost/login/Kasp_proj_new/dice/10_6.png",
"http://localhost/login/Kasp_proj_new/dice/10_7.png",
"http://localhost/login/Kasp_proj_new/dice/10_8.png",
"http://localhost/login/Kasp_proj_new/dice/10_9.png",
"http://localhost/login/Kasp_proj_new/dice/10_10.png",
"http://localhost/login/Kasp_proj_new/dice/100_11.png",
"http://localhost/login/Kasp_proj_new/dice/100_12.png",
"http://localhost/login/Kasp_proj_new/dice/100_13.png",
"http://localhost/login/Kasp_proj_new/dice/100_14.png",
"http://localhost/login/Kasp_proj_new/dice/100_15.png",
"http://localhost/login/Kasp_proj_new/dice/100_16.png",
"http://localhost/login/Kasp_proj_new/dice/100_17.png",
"http://localhost/login/Kasp_proj_new/dice/100_18.png",
"http://localhost/login/Kasp_proj_new/dice/100_19.png",
"http://localhost/login/Kasp_proj_new/dice/100_20.png",
"http://localhost/login/Kasp_proj_new/dice/100_21.png",
"http://localhost/login/Kasp_proj_new/dice/100_22.png",
"http://localhost/login/Kasp_proj_new/dice/100_23.png",
"http://localhost/login/Kasp_proj_new/dice/100_24.png",
"http://localhost/login/Kasp_proj_new/dice/100_25.png",
"http://localhost/login/Kasp_proj_new/dice/100_26.png",
"http://localhost/login/Kasp_proj_new/dice/100_27.png",
"http://localhost/login/Kasp_proj_new/dice/100_28.png",
"http://localhost/login/Kasp_proj_new/dice/100_29.png",
"http://localhost/login/Kasp_proj_new/dice/100_30.png",
"http://localhost/login/Kasp_proj_new/dice/100_31.png",
"http://localhost/login/Kasp_proj_new/dice/100_32.png",
"http://localhost/login/Kasp_proj_new/dice/100_33.png",
"http://localhost/login/Kasp_proj_new/dice/100_34.png",
"http://localhost/login/Kasp_proj_new/dice/100_35.png",
"http://localhost/login/Kasp_proj_new/dice/100_36.png",
"http://localhost/login/Kasp_proj_new/dice/100_37.png",
"http://localhost/login/Kasp_proj_new/dice/100_38.png",
"http://localhost/login/Kasp_proj_new/dice/100_39.png",
"http://localhost/login/Kasp_proj_new/dice/100_40.png",
"http://localhost/login/Kasp_proj_new/dice/100_41.png",
"http://localhost/login/Kasp_proj_new/dice/100_42.png",
"http://localhost/login/Kasp_proj_new/dice/100_43.png",
"http://localhost/login/Kasp_proj_new/dice/100_44.png",
"http://localhost/login/Kasp_proj_new/dice/100_45.png",
"http://localhost/login/Kasp_proj_new/dice/100_46.png",
"http://localhost/login/Kasp_proj_new/dice/100_47.png",
"http://localhost/login/Kasp_proj_new/dice/100_48.png",
"http://localhost/login/Kasp_proj_new/dice/100_49.png",
"http://localhost/login/Kasp_proj_new/dice/100_50.png",
"http://localhost/login/Kasp_proj_new/dice/100_51.png",
"http://localhost/login/Kasp_proj_new/dice/100_52.png",
"http://localhost/login/Kasp_proj_new/dice/100_53.png",
"http://localhost/login/Kasp_proj_new/dice/100_54.png",
"http://localhost/login/Kasp_proj_new/dice/100_55.png",
"http://localhost/login/Kasp_proj_new/dice/100_56.png",
"http://localhost/login/Kasp_proj_new/dice/100_57.png",
"http://localhost/login/Kasp_proj_new/dice/100_58.png",
"http://localhost/login/Kasp_proj_new/dice/100_59.png",
"http://localhost/login/Kasp_proj_new/dice/100_60.png",
"http://localhost/login/Kasp_proj_new/dice/100_61.png",
"http://localhost/login/Kasp_proj_new/dice/100_62.png",
"http://localhost/login/Kasp_proj_new/dice/100_63.png",
"http://localhost/login/Kasp_proj_new/dice/100_64.png",
"http://localhost/login/Kasp_proj_new/dice/100_65.png",
"http://localhost/login/Kasp_proj_new/dice/100_66.png",
"http://localhost/login/Kasp_proj_new/dice/100_67.png",
"http://localhost/login/Kasp_proj_new/dice/100_68.png",
"http://localhost/login/Kasp_proj_new/dice/100_69.png",
"http://localhost/login/Kasp_proj_new/dice/100_70.png",
"http://localhost/login/Kasp_proj_new/dice/100_71.png",
"http://localhost/login/Kasp_proj_new/dice/100_72.png",
"http://localhost/login/Kasp_proj_new/dice/100_73.png",
"http://localhost/login/Kasp_proj_new/dice/100_74.png",
"http://localhost/login/Kasp_proj_new/dice/100_75.png",
"http://localhost/login/Kasp_proj_new/dice/100_76.png",
"http://localhost/login/Kasp_proj_new/dice/100_77.png",
"http://localhost/login/Kasp_proj_new/dice/100_78.png",
"http://localhost/login/Kasp_proj_new/dice/100_79.png",
"http://localhost/login/Kasp_proj_new/dice/100_80.png",
"http://localhost/login/Kasp_proj_new/dice/100_81.png",
"http://localhost/login/Kasp_proj_new/dice/100_82.png",
"http://localhost/login/Kasp_proj_new/dice/100_83.png",
"http://localhost/login/Kasp_proj_new/dice/100_84.png",
"http://localhost/login/Kasp_proj_new/dice/100_85.png",
"http://localhost/login/Kasp_proj_new/dice/100_86.png",
"http://localhost/login/Kasp_proj_new/dice/100_87.png",
"http://localhost/login/Kasp_proj_new/dice/100_88.png",
"http://localhost/login/Kasp_proj_new/dice/100_89.png",
"http://localhost/login/Kasp_proj_new/dice/100_90.png",
"http://localhost/login/Kasp_proj_new/dice/100_91.png",
"http://localhost/login/Kasp_proj_new/dice/100_92.png",
"http://localhost/login/Kasp_proj_new/dice/100_93.png",
"http://localhost/login/Kasp_proj_new/dice/100-94.png",
"http://localhost/login/Kasp_proj_new/dice/100_95.png",
"http://localhost/login/Kasp_proj_new/dice/100_96.png",
"http://localhost/login/Kasp_proj_new/dice/100_97.png",
"http://localhost/login/Kasp_proj_new/dice/100_98.png",
"http://localhost/login/Kasp_proj_new/dice/100_99.png",
"http://localhost/login/Kasp_proj_new/dice/100_100.png"];

const dices = [ d4,
d6,
d8,
d10,
d12,
d20,
d100];

const ids = ["d4",
"d6",
"d8",
"d10",
"d12",
"d20",
"d100"];

function roll(x, maximal)
{
  let die = document.getElementById(ids[x]);
  die.classList.add("shake");

  setTimeout(function() {
    die.classList.remove("shake");
    let value = Math.floor(Math.random()*maximal);
    document.getElementById(ids[x]).setAttribute("src", dices[x][value]);
  },
  1000  
  );
}
